### ISSUE TITLE
custom url を entry の header で指定できるようにしてほしい

### ISSUE THREAD

**Issue by chaspy** [hatena/Hatena-Blog-Workflows-Boilerplate#41]
いつも便利に使わせていただいております！

記事投稿する際、ヘッダーにこのような項目がありますが、

```yaml
---
Title: 開発組織が事業貢献するには
EditURL: https://blog.hatena.ne.jp/quipper-ja/quipper.hatenablog.com/atom/entry/111111
PreviewURL: https://blog.studysapuri.jp/draft/entry/xxxxxxx
Draft: true
---
```

ここで CustomURL を指定できるようにしたいです。

背景として、我々はこの Workflow を使っていろんな人が Blog を書いているのですが、
最後 custom URL の指定と投稿予約だけは GUI でやる必要があります。
この制約上、全員に個人のはてなアカウントを作成してもらっており、可能ならば Pull Request で完結させたいです。

api を見たところ、投稿予約は API にないので難しそうですが、custom URL は可能では？と思った次第です。
https://developer.hatena.ne.jp/ja/documents/blog/apis/atom/#%E3%83%96%E3%83%AD%E3%82%B0%E3%82%A8%E3%83%B3%E3%83%88%E3%83%AA%E3%81%AE%E7%B7%A8%E9%9B%86

ご検討よろしくお願いします。
